### ISSUE TITLE
Refactoring and Task List - Beta 10

### ISSUE THREAD

**Issue by mariodivece** [unosquare/ffmediaelement#122]
Currently, ffme.common is using MediaElementCore as means for cross-platform implementations.
Maybe use a shared code project as opposed to a separate assembly to accomplish portability.

Checklist:
- [x] Remove DEBUG directives
- [x] Improve FFmpeg registration
- [x] Remove Globals (Properly expose public methods (MediaCoreProperty enum))
- [x] Verify Property Propagation: Container to Engine to MediaElement
- [x] Remove SetDllDirectory dependency
- [x] Try to remove Constants and dd TimerScheduling to Defaults
- [x] If possible, make no UI Calls from MediaEngine and cleanup IPlatform
- [x] Make MediaEngine UI-independent
- [x] Remove ActionPriority altogether
- [x] If possible, remove propertyupdatetimer The key is to keep a global download buffer stat
- [x] Stopwatch keep time without rest in blockrendering worker
- [x] Polish FrameDecodingWorker logic
- [x] DownloadCacheLength vs IsLiveStream vs IsNetworkStream
- [x] Move property updates out of the block rendering worker because it runs too often.

**Comment by tpetrina** [comment]
Shared project has its benefits in a sense that you can use #ifdef to use per platform implementation. However, by using common library that is also .NET Standard you get a _cleaner_ architecture. It is also possible to use ffme.common in other .NET Standard libraries aka common code for other projects. Think having a cross platform app and putting business logic in netstandard lib - it can now reference common project.

What is the primary driver for this switch?

**Comment by mariodivece** [comment]
@tpetrina ok, like I said in my original post:
"Maybe use a shared code project..."

Certainly an item for discussion and not a final determination.

**Comment by mariodivece** [comment]
I have inspected cross-platform implementation of the MediaElement control and I think leaving separate assemblies is the right approach. The only thing I think is missing is the formalization of a Platfrom Connector that serves as bridging logic for the different platforms.

**Comment by mariodivece** [comment]
Note to self: Rename MediaElementCore to MediaEngine and make internal stuff available for other implementations.

**Comment by tpetrina** [comment]
Utils should also be cleaned up and possibly moved to per platform implementation. I am talking about registering ffmpeg libraries.

**Comment by mariodivece** [comment]
yep ffmpeg lib registration is certainly something that needs to improve. I agree

**Comment by mariodivece** [comment]
@tpetrina Lots of work has gone into this. Could you please check and verify the sample MacOS implementation you provided still works and adjust accordingly? Thanks!

**Comment by tpetrina** [comment]
Will do!

On 8 Jan 2018, at 22:38, Mario Di Vece <notifications@github.com<mailto:notifications@github.com>> wrote:


@tpetrina<https://github.com/tpetrina> Lots of work has gone into this. Could you please check and verify the sample MacOS implementation you provided still works and adjust accordingly? Thanks!

**Comment by tpetrina** [comment]
Mac sample doesn't work, fixing it.

**Comment by mariodivece** [comment]
Closing. RC1 is now here!
