### ISSUE TITLE
Various improvements and code cleanup for 2.70 Release

### ISSUE THREAD

**Issue by mariodivece** [unosquare/ffmediaelement#250]
# Task List

 - [x] Rewrite CommandManager for better command handling using Promises
 - [x] Finish CommandManager.Dispose implementation and verify caller. Don't forget the interrupt
 - [x] Finish CommandManager IsDisposed backing
 - [x] Ensure new Commands Documentation is complete
 - [x] Remove IsTaskCancellationPending
 - [x] Automate IsSeeking via CommandManager
 - [x] Expose SeekingDone.WaitOne via CommandManager
 - [x] Expose HasDecoderSeeked via CommandManager
 - [x] Explore: Recover from interrupt callback possible? (Does not seem possible as the InputContext gets aborted)
 - [x] Explore: Close priority immediate (interrupt and cancel workers)
 - [x] SendOnMediaInitializing and other send methods send argument-less
 - [x] HasMediaEnded not working when unloadedbahavior is pause
 - [x] Remove GC.SuppressFinalize and add Dispose locking
 - [x] Improve UpdateBufferingProperties
 - [x] Add frame decoding callback
 - [x] Check on ResetMediaProperties (see private setters)
 - [x] Use ISyncLockers instead of locks wherever possible
 - [x] Replace non-thread-safe IsDsiposed properties with ISyncLocker IsDiposed property whenrever possible
 - [x] PacketQueue simplify and correct dispose Logic
 - [x] Improve ISyncLocker (atomic boolean and such)
 - [x] MediaEngineState check SyncLocks for efficiency
 - [x] MediaEngineState check and make access more efficient when accessing components.
 - [x] Review Excessive locking (only provide real-time values when needed)
 - [x] Complete dynamic property updates MediaEngineState.UpdateDynamicBlockProperties
 - [x] CC Rendering is now out of sync
 - [x] Review ReadingCycle.WaitOne for UDP streams (is this necessary?)
 - [x] PendingSeeks not synced up because the awaiter might already be active
 - [x] ChangeMedia not resuming playback
 - [x] Remove Console.WriteLines STATE CHANGED: message logging
 - [x] Review PositionChanged event firing
 - [x] Possibly try to automate IsSeeking from commandmanager
 - [x] Derive Stop Command from SeekCommand
 - [x] Homegeneous handling of Clock.Update/Reset and UpdatePosition()
 - [x] GuessedByteRate is incorrect producing very large Buffer and Download cache values.
 - [x] VideoFrameLength and FrameDuration properties. Also compute defaults in PositionCurrent, PositionPrevious PositionNext
 - [x] IsMonotonic dependency
 - [x] Review Media Start Offset (according to main)
 - [x] Improve the IsBuffering State activation
 - [x] After end of media, audio write tag is not invalidated
 - [x] See checks: https://app.codacy.com/project/UnosquareLabs/ffmediaelement/dashboard
 - [x] Remove fixed statements
 - [x] Improve Stream Seek Logic by analyzing start time of frames.

**Comment by mariodivece** [comment]
MPEG-DASH Test Streams:
http://rdmedia.bbc.co.uk/

**Comment by mariodivece** [comment]
HLS Test Streams:
http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8
http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8

**Comment by mariodivece** [comment]
getting error randomly when locking DS buffer (Clear). Stack trace:
```
   at Unosquare.FFME.Rendering.Wave.DirectSoundPlayer.DirectSound.IDirectSoundBuffer.Lock(Int32 dwOffset, UInt32 dwBytes, IntPtr& audioPtr1, Int32& audioBytes1, IntPtr& audioPtr2, Int32& audioBytes2, DirectSoundBufferLockFlag dwFlags)
   at Unosquare.FFME.Rendering.Wave.DirectSoundPlayer.ClearBackBuffer() in C:\projects\ffmediaelement\Unosquare.FFME.Windows\Rendering\Wave\DirectSoundPlayer.cs:line 416
   at Unosquare.FFME.Rendering.Wave.DirectSoundPlayer.Clear() in C:\projects\ffmediaelement\Unosquare.FFME.Windows\Rendering\Wave\DirectSoundPlayer.cs:line 141
   at Unosquare.FFME.Rendering.AudioRenderer.Seek() in C:\projects\ffmediaelement\Unosquare.FFME.Windows\Rendering\AudioRenderer.cs:line 294
   at Unosquare.FFME.MediaEngine.InvalidateRenderer(MediaType t)
   at Unosquare.FFME.MediaEngine.<>c__DisplayClass148_0.<StartBlockRenderingWorker>b__0(Object s)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

**Comment by mariodivece** [comment]
PR Checks: https://app.codacy.com/app/UnosquareLabs/ffmediaelement/pullRequest?prid=2024830
