### ISSUE TITLE
Various improvements and code cleanup for 2.80 Release

### ISSUE THREAD

**Issue by mariodivece** [unosquare/ffmediaelement#281]
# Task List
 - [x] Possibly remove delay provider from FrameDecoding worker and deprecate delay provider entirely
 - [x] Check circularbuffer for overlaps
 - [x] Check for misuse of MediaCore.State inside mediacore
 - [x] Verify PositionStep calculation for audio
 - [x] Verify video SMTPE calculation
 - [x] Cancellable Seek Command whenever a new seek is in queue.
 - [x] Some issues with VU-meter not updating in LEgacyAudioMode
 - [x] Some issues with over-buffering DirectSound driver and audio repeated or cut sometimes
 - [x] Seeking forward might already have packets. Explore the possibility of simply decoding the already available packets.
 - [x] DPI for BitmapBuffer
 - [x] Possibly try to automate task delays via renderer or maybe decoder needs via IWaitEvent
 - [x] Possibly try to automate StateUpdates from commandmanager
needed.
 - [x] Encapsulate workers into their own classes
 - [x] Frame stepping back is skipping 1 frame (maybe because of the new docoding worker logic?

**Comment by mariodivece** [comment]
New NuGet will be released today.
