### ISSUE TITLE
Checklist for Release 3.40

### ISSUE THREAD

**Issue by mariodivece** [unosquare/ffmediaelement#339]
Misc. Checklist (carried over from previous release)

 - [ ] Revise Clear upon Seeking on AudioRenderer drivers.
 - [ ] Remove SA1401 pragmas
 - [ ] Verify ISyncLocker usage (1 write thread multiple read threads) Replace with monitors when not 
 - [ ] Disposable Pattern with AtomicBoolean (IDisposableEx : IDisposable)
 - [ ] State getters vs state setters (void vs return value)
 - [ ] Recheck thread synchronization
 - [x] Seeking displays all seek frames (again, maybe because of the new frame decoding logic)
 - [ ] Explore the possibility of synclocks on decoding plus rendering to synchronize them.
 - [x] Implement scrubbing enabled property from engine itself (BlockRenderingWorker)
See: https://stackoverflow.com/questions/47014586/different-p-invoke-entry-point-for-net-vs-net-core-2
 - [x] The playlist is not working properly, confising file:// and simple file paths. It should really be all full URLs
